#!/usr/bin/env node
/**
 * Wrap WAV files as `<name>.wav.js` sidecars for file:// distribution
 * (specs/168-spectrograph-player, research.md §5.3).
 *
 * From a file:// page a browser will not let a script fetch a sibling .wav, but
 * it will load a sibling .js. Each sidecar registers the file's bytes, base64
 * encoded, on `window.GramFrameAudio` under the WAV's basename; GramFrame
 * looks for it only after fetch has failed, so pages served over HTTP never
 * need it.
 *
 *   node scripts/wav2js.mjs sample/audio/*.wav
 *
 * Writes each sidecar next to its source and prints the sizes.
 */

import { readFileSync, writeFileSync, statSync } from 'node:fs'
import { basename } from 'node:path'

const files = process.argv.slice(2)
if (files.length === 0) {
  console.error('usage: node scripts/wav2js.mjs <file.wav> [more.wav …]')
  process.exit(1)
}

for (const file of files) {
  const bytes = readFileSync(file)
  if (bytes.length < 12 || bytes.toString('latin1', 0, 4) !== 'RIFF' || bytes.toString('latin1', 8, 12) !== 'WAVE') {
    console.error(`skipping ${file}: not a RIFF/WAVE file`)
    continue
  }
  const key = JSON.stringify(basename(file))
  const out = `${file}.js`
  writeFileSync(out,
    '// Generated by scripts/wav2js.mjs — the bytes of ' + basename(file) + ' for file:// pages.\n' +
    'window.GramFrameAudio = window.GramFrameAudio || {};\n' +
    `window.GramFrameAudio[${key}] = "${bytes.toString('base64')}";\n`
  )
  console.log(`${out}: ${(statSync(out).size / 1024).toFixed(0)} KB (from ${(bytes.length / 1024).toFixed(0)} KB)`)
}
